name: Build and Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master # CHANGE if your default branch is different

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Angular project
      - name: Build Angular app
        run: |
          npm run build -- --configuration production --base-href "/task-wheel/"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/task-wheel/browser